# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Richiedente',
            fields=[
                ('idRichiedente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cognome', models.CharField(blank=True, max_length=50, null=True)),
                ('regione', models.CharField(blank=True, max_length=50, null=True)),
                ('citta', models.CharField(blank=True, max_length=50, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('foto', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
