# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('idOggetto', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(blank=True, max_length=50, null=True)),
                ('regione', models.CharField(blank=True, max_length=50, null=True)),
                ('citta', models.CharField(blank=True, max_length=50, null=True)),
                ('descrizione', models.TextField(blank=True, max_length=250, null=True)),
                ('prezzo', models.CharField(blank=True, choices=[('10 Euro', '10 Euro'), ('20 EUro', '20 Euro'), ('30 EUro', '30 Euro')], max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='richiedente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('Uomo', 'Uomo'), ('Donna', 'Donna')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='richiedente',
            name='valutazione',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='richiedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Richiedente'),
        ),
    ]
