# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171008_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richiedente',
            options={'verbose_name': 'Richiedente', 'verbose_name_plural': 'Richiedenti'},
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='richiedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oggetti', to='app.Richiedente'),
        ),
    ]
